// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Blog Listing documents
 */
interface BlogListingDocumentData {
  /**
   * Heading field in *Blog Listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_listing.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * sub heading field in *Blog Listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_listing.sub_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField /**
   * SEO Title field in *Blog Listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_listing.seo_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  seo_title: prismic.RichTextField;

  /**
   * SEO Description field in *Blog Listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_listing.seo_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  seo_description: prismic.RichTextField;
}

/**
 * Blog Listing document from Prismic
 *
 * - **API ID**: `blog_listing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogListingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogListingDocumentData>,
    "blog_listing",
    Lang
  >;

/**
 * Content for CTA-iframe documents
 */
interface CtaIframeDocumentData {
  /**
   * Embed Link field in *CTA-iframe*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: cta-iframe.embed_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  embed_link: prismic.EmbedField;

  /**
   * below text field in *CTA-iframe*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta-iframe.below_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  below_text: prismic.RichTextField;

  /**
   * After CTA field in *CTA-iframe*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta-iframe.after_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  after_cta: prismic.RichTextField;
}

/**
 * CTA-iframe document from Prismic
 *
 * - **API ID**: `cta-iframe`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CtaIframeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CtaIframeDocumentData>,
    "cta-iframe",
    Lang
  >;

/**
 * Slice for *Entrada Post → Slice zone*
 */
export type EntradaPostDocumentDataBodyTextSlice = prismic.Slice<
  "text",
  Record<string, never>,
  never
>;

type EntradaPostDocumentDataBodySlice = EntradaPostDocumentDataBodyTextSlice;

/**
 * Content for Entrada Post documents
 */
interface EntradaPostDocumentData {
  /**
   * Título Página field in *Entrada Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Tittle
   * - **API ID Path**: entrada_post.page_tittle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  page_tittle: prismic.TitleField;

  /**
   * H1 de la página field in *Entrada Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: H1 de la página
   * - **API ID Path**: entrada_post.h1_de_la_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  h1_de_la_pagina: prismic.TitleField;

  /**
   * Content field in *Entrada Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: entrada_post.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice zone field in *Entrada Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: entrada_post.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<EntradaPostDocumentDataBodySlice> /**
   * SEO Titulo field in *Entrada Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: entrada_post.seo_titulo
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  seo_titulo: prismic.KeyTextField;

  /**
   * SEO Descripción field in *Entrada Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: entrada_post.seo_descripcion
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_descripcion: prismic.KeyTextField;
}

/**
 * Entrada Post document from Prismic
 *
 * - **API ID**: `entrada_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EntradaPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EntradaPostDocumentData>,
    "entrada_post",
    Lang
  >;

/**
 * Item in *Footer → Legal*
 */
export interface FooterDocumentDataLegalItem {
  /**
   * text for legal link field in *Footer → Legal*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal[].text_for_legal_link
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_for_legal_link: prismic.RichTextField;

  /**
   * Link field in *Footer → Legal*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Footer → Slice zone → Call to action → Primary*
 */
export interface FooterDocumentDataBodyCallToActionSlicePrimary {
  /**
   * CTA Introduction field in *Footer → Slice zone → Call to action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.body[].call_to_action.primary.cta_introduction
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_introduction: prismic.RichTextField;

  /**
   * Small Image CTA field in *Footer → Slice zone → Call to action → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.body[].call_to_action.primary.small_image_cta
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  small_image_cta: prismic.ImageField<never>;

  /**
   * Main Text field in *Footer → Slice zone → Call to action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.body[].call_to_action.primary.main_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_text: prismic.RichTextField;

  /**
   * Secondary Text field in *Footer → Slice zone → Call to action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.body[].call_to_action.primary.secondary_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  secondary_text: prismic.RichTextField;

  /**
   * Below Text field in *Footer → Slice zone → Call to action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.body[].call_to_action.primary.below_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  below_text: prismic.RichTextField;

  /**
   * Destination Link of CTA field in *Footer → Slice zone → Call to action → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.body[].call_to_action.primary.destination_link_of_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  destination_link_of_cta: prismic.LinkField;

  /**
   * After CTA field in *Footer → Slice zone → Call to action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.body[].call_to_action.primary.after_cta
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  after_cta: prismic.RichTextField;
}

/**
 * Slice for *Footer → Slice zone*
 */
export type FooterDocumentDataBodyCallToActionSlice = prismic.Slice<
  "call_to_action",
  Simplify<FooterDocumentDataBodyCallToActionSlicePrimary>,
  never
>;

/**
 * Primary content in *Footer → Slice zone → Bloques → Primary*
 */
export interface FooterDocumentDataBodyBloquesSlicePrimary {
  /**
   * title of this block field in *Footer → Slice zone → Bloques → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.body[].bloques.primary.title_of_this_block
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_of_this_block: prismic.RichTextField;
}

/**
 * Item content in *Footer → Slice zone → Bloques → Items*
 */
export interface FooterDocumentDataBodyBloquesSliceItem {
  /**
   * Name of this block field in *Footer → Slice zone → Bloques → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.body[].bloques.items.name_of_this_block
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name_of_this_block: prismic.RichTextField;

  /**
   * Link field in *Footer → Slice zone → Bloques → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.body[].bloques.items.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Slice for *Footer → Slice zone*
 */
export type FooterDocumentDataBodyBloquesSlice = prismic.Slice<
  "bloques",
  Simplify<FooterDocumentDataBodyBloquesSlicePrimary>,
  Simplify<FooterDocumentDataBodyBloquesSliceItem>
>;

type FooterDocumentDataBodySlice =
  | FooterDocumentDataBodyCallToActionSlice
  | FooterDocumentDataBodyBloquesSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * disclaimer field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.disclaimer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  disclaimer: prismic.RichTextField;

  /**
   * Legal field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  legal: prismic.GroupField<Simplify<FooterDocumentDataLegalItem>>;

  /**
   * Slice zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<FooterDocumentDataBodySlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Título field in *home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título
   * - **API ID Path**: home.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.TitleField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Primary content in *Homepage → Slice zone → Hero → Primary*
 */
export interface HomepageDocumentDataBodyHeroSlicePrimary {
  /**
   * Title field in *Homepage → Slice zone → Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *Homepage → Slice zone → Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].hero.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.TitleField;

  /**
   * video field in *Homepage → Slice zone → Hero → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].hero.primary.video
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField;

  /**
   * Background Image field in *Homepage → Slice zone → Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].hero.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyHeroSlice = prismic.Slice<
  "hero",
  Simplify<HomepageDocumentDataBodyHeroSlicePrimary>,
  never
>;

/**
 * Primary content in *Homepage → Slice zone → Call to action → Primary*
 */
export interface HomepageDocumentDataBodyCallToActionSlicePrimary {
  /**
   * Title field in *Homepage → Slice zone → Call to action → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].call_to_action.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title1: prismic.TitleField;

  /**
   * Description field in *Homepage → Slice zone → Call to action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].call_to_action.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Destination page field in *Homepage → Slice zone → Call to action → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].call_to_action.primary.destination_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  destination_page: prismic.ContentRelationshipField<"page">;

  /**
   * Destination label text field in *Homepage → Slice zone → Call to action → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].call_to_action.primary.destination_label_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  destination_label_text: prismic.KeyTextField;

  /**
   * Image field in *Homepage → Slice zone → Call to action → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].call_to_action.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyCallToActionSlice = prismic.Slice<
  "call_to_action",
  Simplify<HomepageDocumentDataBodyCallToActionSlicePrimary>,
  never
>;

type HomepageDocumentDataBodySlice =
  | HomepageDocumentDataBodyHeroSlice
  | HomepageDocumentDataBodyCallToActionSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<HomepageDocumentDataBodySlice> /**
   * Título field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.seo_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  seo_title: prismic.KeyTextField;

  /**
   * Descripción field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.seo_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Primary content in *Landing Page → Slice Zone → Hero Landing → Primary*
 */
export interface LandingPageDocumentDataBodyHeroLandingSlicePrimary {
  /**
   * Left Side Icon field in *Landing Page → Slice Zone → Hero Landing → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].hero_landing.primary.left_side_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  left_side_icon: prismic.ImageField<never>;

  /**
   * h1 field in *Landing Page → Slice Zone → Hero Landing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: h1
   * - **API ID Path**: landing_page.body[].hero_landing.primary.h1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  h1: prismic.RichTextField;

  /**
   * Header field in *Landing Page → Slice Zone → Hero Landing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].hero_landing.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.RichTextField;

  /**
   * Sub Header field in *Landing Page → Slice Zone → Hero Landing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].hero_landing.primary.sub_header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_header: prismic.RichTextField;

  /**
   * Thumbneil Image or Video light weight field in *Landing Page → Slice Zone → Hero Landing → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: Very light weight video to insert (max 9 sec)
   * - **API ID Path**: landing_page.body[].hero_landing.primary.video_light_weight
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video_light_weight: prismic.EmbedField;

  /**
   * Long version of video field in *Landing Page → Slice Zone → Hero Landing → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: Video to show in PopUp (VIMEO or YouTube)
   * - **API ID Path**: landing_page.body[].hero_landing.primary.long_version_of_video
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  long_version_of_video: prismic.EmbedField;

  /**
   * Featured In field in *Landing Page → Slice Zone → Hero Landing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: If blank no show
   * - **API ID Path**: landing_page.body[].hero_landing.primary.featured_in
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featured_in: prismic.RichTextField;

  /**
   * Featured in Image field in *Landing Page → Slice Zone → Hero Landing → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].hero_landing.primary.featured_in_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_in_image: prismic.ImageField<never>;
}

/**
 * Slice for *Landing Page → Slice Zone*
 */
export type LandingPageDocumentDataBodyHeroLandingSlice = prismic.Slice<
  "hero_landing",
  Simplify<LandingPageDocumentDataBodyHeroLandingSlicePrimary>,
  never
>;

/**
 * Primary content in *Landing Page → Slice Zone → Call to action → Primary*
 */
export interface LandingPageDocumentDataBodyCallToActionSlicePrimary {
  /**
   * Small Image CTA field in *Landing Page → Slice Zone → Call to action → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].call_to_action.primary.small_image_cta
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  small_image_cta: prismic.ImageField<never>;

  /**
   * Main Text field in *Landing Page → Slice Zone → Call to action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].call_to_action.primary.main_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_text: prismic.RichTextField;

  /**
   * Secondary Text field in *Landing Page → Slice Zone → Call to action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].call_to_action.primary.secondary_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  secondary_text: prismic.RichTextField;

  /**
   * Below Text field in *Landing Page → Slice Zone → Call to action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].call_to_action.primary.below_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  below_text: prismic.RichTextField;

  /**
   * Destination Link of CTA field in *Landing Page → Slice Zone → Call to action → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].call_to_action.primary.destination_link_of_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  destination_link_of_cta: prismic.LinkField;

  /**
   * After CTA field in *Landing Page → Slice Zone → Call to action → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].call_to_action.primary.after_cta
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  after_cta: prismic.RichTextField;
}

/**
 * Slice for *Landing Page → Slice Zone*
 */
export type LandingPageDocumentDataBodyCallToActionSlice = prismic.Slice<
  "call_to_action",
  Simplify<LandingPageDocumentDataBodyCallToActionSlicePrimary>,
  never
>;

/**
 * Primary content in *Landing Page → Slice Zone → Content With Image → Primary*
 */
export interface LandingPageDocumentDataBodyContentWithImageSlicePrimary {
  /**
   * Small Image field in *Landing Page → Slice Zone → Content With Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].content_with_image.primary.small_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  small_image: prismic.ImageField<never>;

  /**
   * Title field in *Landing Page → Slice Zone → Content With Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].content_with_image.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Does it have date? field in *Landing Page → Slice Zone → Content With Image → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: landing_page.body[].content_with_image.primary.does_it_have_date_
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  does_it_have_date_: prismic.BooleanField;

  /**
   * Text field in *Landing Page → Slice Zone → Content With Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].content_with_image.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Slice for *Landing Page → Slice Zone*
 */
export type LandingPageDocumentDataBodyContentWithImageSlice = prismic.Slice<
  "content_with_image",
  Simplify<LandingPageDocumentDataBodyContentWithImageSlicePrimary>,
  never
>;

/**
 * Primary content in *Landing Page → Slice Zone → Video Reviews → Primary*
 */
export interface LandingPageDocumentDataBodyVideoReviewsSlicePrimary {
  /**
   * Intro To Reviews field in *Landing Page → Slice Zone → Video Reviews → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].video_reviews.primary.intro_to_reviews
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  intro_to_reviews: prismic.RichTextField;
}

/**
 * Item content in *Landing Page → Slice Zone → Video Reviews → Items*
 */
export interface LandingPageDocumentDataBodyVideoReviewsSliceItem {
  /**
   * Image of Review field in *Landing Page → Slice Zone → Video Reviews → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].video_reviews.items.image_of_review
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_of_review: prismic.ImageField<never>;

  /**
   * Name of Reviwer field in *Landing Page → Slice Zone → Video Reviews → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].video_reviews.items.name_of_reviwer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name_of_reviwer: prismic.RichTextField;

  /**
   * Description of review field in *Landing Page → Slice Zone → Video Reviews → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].video_reviews.items.description_of_review
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_of_review: prismic.RichTextField;

  /**
   * CTA to watch video field in *Landing Page → Slice Zone → Video Reviews → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].video_reviews.items.cta_to_watch_video
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_to_watch_video: prismic.RichTextField;

  /**
   * Video PopUp field in *Landing Page → Slice Zone → Video Reviews → Items*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].video_reviews.items.video_popup
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video_popup: prismic.EmbedField;
}

/**
 * Slice for *Landing Page → Slice Zone*
 */
export type LandingPageDocumentDataBodyVideoReviewsSlice = prismic.Slice<
  "video_reviews",
  Simplify<LandingPageDocumentDataBodyVideoReviewsSlicePrimary>,
  Simplify<LandingPageDocumentDataBodyVideoReviewsSliceItem>
>;

/**
 * Primary content in *Landing Page → Slice Zone → Lead Magnet Book → Primary*
 */
export interface LandingPageDocumentDataBodyLeadMagnetBookSlicePrimary {
  /**
   * Intro field in *Landing Page → Slice Zone → Lead Magnet Book → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].lead_magnet_book.primary.intro
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  intro: prismic.RichTextField;

  /**
   * Title field in *Landing Page → Slice Zone → Lead Magnet Book → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].lead_magnet_book.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Lead Magnet Image field in *Landing Page → Slice Zone → Lead Magnet Book → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].lead_magnet_book.primary.lead_magnet_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  lead_magnet_image: prismic.ImageField<never>;

  /**
   * CTA field in *Landing Page → Slice Zone → Lead Magnet Book → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].lead_magnet_book.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta: prismic.RichTextField;

  /**
   * WebHook To Save Info field in *Landing Page → Slice Zone → Lead Magnet Book → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].lead_magnet_book.primary.webhook_to_save_info
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  webhook_to_save_info: prismic.EmbedField;
}

/**
 * Slice for *Landing Page → Slice Zone*
 */
export type LandingPageDocumentDataBodyLeadMagnetBookSlice = prismic.Slice<
  "lead_magnet_book",
  Simplify<LandingPageDocumentDataBodyLeadMagnetBookSlicePrimary>,
  never
>;

/**
 * Primary content in *Landing Page → Slice Zone → Faqs → Primary*
 */
export interface LandingPageDocumentDataBodyFaqsSlicePrimary {
  /**
   * title field in *Landing Page → Slice Zone → Faqs → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].faqs.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Item content in *Landing Page → Slice Zone → Faqs → Items*
 */
export interface LandingPageDocumentDataBodyFaqsSliceItem {
  /**
   * Question in h2 field in *Landing Page → Slice Zone → Faqs → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].faqs.items.question_in_h2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question_in_h2: prismic.RichTextField;

  /**
   * Answer Rich Text field in *Landing Page → Slice Zone → Faqs → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].faqs.items.answer_rich_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer_rich_text: prismic.RichTextField;
}

/**
 * Slice for *Landing Page → Slice Zone*
 */
export type LandingPageDocumentDataBodyFaqsSlice = prismic.Slice<
  "faqs",
  Simplify<LandingPageDocumentDataBodyFaqsSlicePrimary>,
  Simplify<LandingPageDocumentDataBodyFaqsSliceItem>
>;

/**
 * Primary content in *Landing Page → Slice Zone → Team → Primary*
 */
export interface LandingPageDocumentDataBodyTeamSlicePrimary {
  /**
   * Team Introduction field in *Landing Page → Slice Zone → Team → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].team.primary.team_introduction
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  team_introduction: prismic.RichTextField;
}

/**
 * Item content in *Landing Page → Slice Zone → Team → Items*
 */
export interface LandingPageDocumentDataBodyTeamSliceItem {
  /**
   * Team Member Image field in *Landing Page → Slice Zone → Team → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].team.items.team_member_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  team_member_image: prismic.ImageField<never>;

  /**
   * Team Member Name field in *Landing Page → Slice Zone → Team → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].team.items.team_member_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  team_member_name: prismic.RichTextField;

  /**
   * Team Member Position field in *Landing Page → Slice Zone → Team → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].team.items.team_member_position
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  team_member_position: prismic.RichTextField;
}

/**
 * Slice for *Landing Page → Slice Zone*
 */
export type LandingPageDocumentDataBodyTeamSlice = prismic.Slice<
  "team",
  Simplify<LandingPageDocumentDataBodyTeamSlicePrimary>,
  Simplify<LandingPageDocumentDataBodyTeamSliceItem>
>;

/**
 * Primary content in *Landing Page → Slice Zone → Testimonials → Primary*
 */
export interface LandingPageDocumentDataBodyTestimonialsSlicePrimary {
  /**
   * All Testimonials field in *Landing Page → Slice Zone → Testimonials → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].testimonials.primary.all_testimonials
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  all_testimonials: prismic.ContentRelationshipField<"testimonials_all_of_th">;
}

/**
 * Slice for *Landing Page → Slice Zone*
 */
export type LandingPageDocumentDataBodyTestimonialsSlice = prismic.Slice<
  "testimonials",
  Simplify<LandingPageDocumentDataBodyTestimonialsSlicePrimary>,
  never
>;

/**
 * Primary content in *Landing Page → Slice Zone → CTA - iframe → Primary*
 */
export interface LandingPageDocumentDataBodyCtaIframeSlicePrimary {
  /**
   * small image above CTA field in *Landing Page → Slice Zone → CTA - iframe → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].cta_-_iframe.primary.small_image_above_cta
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  small_image_above_cta: prismic.ImageField<never>;

  /**
   * iFrame field in *Landing Page → Slice Zone → CTA - iframe → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].cta_-_iframe.primary.iframe
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  iframe: prismic.KeyTextField;

  /**
   * below CTA field in *Landing Page → Slice Zone → CTA - iframe → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].cta_-_iframe.primary.below_cta
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  below_cta: prismic.RichTextField;

  /**
   * After CTA field in *Landing Page → Slice Zone → CTA - iframe → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[].cta_-_iframe.primary.after_cta
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  after_cta: prismic.RichTextField;
}

/**
 * Slice for *Landing Page → Slice Zone*
 */
export type LandingPageDocumentDataBodyCtaIframeSlice = prismic.Slice<
  "cta_-_iframe",
  Simplify<LandingPageDocumentDataBodyCtaIframeSlicePrimary>,
  never
>;

/**
 * Primary content in *Landing Page → Slice Zone → Book a Session Script → Primary*
 */
export interface LandingPageDocumentDataBodyBookASessionScriptSlicePrimary {
  /**
   * run script field in *Landing Page → Slice Zone → Book a Session Script → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: landing_page.body[].book_a_session_script.primary.run_script
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  run_script: prismic.BooleanField;
}

/**
 * Slice for *Landing Page → Slice Zone*
 */
export type LandingPageDocumentDataBodyBookASessionScriptSlice = prismic.Slice<
  "book_a_session_script",
  Simplify<LandingPageDocumentDataBodyBookASessionScriptSlicePrimary>,
  never
>;

type LandingPageDocumentDataBodySlice =
  | IframeSlice
  | LandingPageDocumentDataBodyHeroLandingSlice
  | LandingPageDocumentDataBodyCallToActionSlice
  | LandingPageDocumentDataBodyContentWithImageSlice
  | LandingPageDocumentDataBodyVideoReviewsSlice
  | LandingPageDocumentDataBodyLeadMagnetBookSlice
  | LandingPageDocumentDataBodyFaqsSlice
  | LandingPageDocumentDataBodyTeamSlice
  | LandingPageDocumentDataBodyTestimonialsSlice
  | LandingPageDocumentDataBodyCtaIframeSlice
  | LandingPageDocumentDataBodyBookASessionScriptSlice;

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<LandingPageDocumentDataBodySlice> /**
   * SEO Title field in *Landing Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.seo_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  seo_title: prismic.TitleField;

  /**
   * SEO Description field in *Landing Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.seo_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  seo_description: prismic.TitleField;

  /**
   * html code field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.html_code
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  html_code: prismic.KeyTextField;

  /**
   * html rich text field in *Landing Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.html_rich_text
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  html_rich_text: prismic.RichTextField;

  /**
   * embed html field in *Landing Page*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.embed_html
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  embed_html: prismic.EmbedField;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Item in *Header → Menu items*
 */
export interface NavigationDocumentDataMenuItemsItem {
  /**
   * Label field in *Header → Menu items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu_items[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Small Label field in *Header → Menu items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu_items[].small_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  small_label: prismic.RichTextField;

  /**
   * The Link field in *Header → Menu items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu_items[].the_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  the_link: prismic.LinkField;
}

/**
 * Item in *Header → Socials Networks*
 */
export interface NavigationDocumentDataSocialsNetworksItem {
  /**
   * Link to Social field in *Header → Socials Networks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.socials_networks[].link_to_social
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_to_social: prismic.LinkField;

  /**
   * Icon Social field in *Header → Socials Networks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.socials_networks[].icon_social
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon_social: prismic.ImageField<never>;
}

/**
 * Content for Header documents
 */
interface NavigationDocumentData {
  /**
   * Logo Header field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.logo_header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_header: prismic.ImageField<never>;

  /**
   * Call Us Now Text field in *Header*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.call_us_now_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  call_us_now_text: prismic.RichTextField;

  /**
   * Call us now Phone field in *Header*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.call_us_now_phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  call_us_now_phone: prismic.RichTextField;

  /**
   * Menu items field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.menu_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_items: prismic.GroupField<Simplify<NavigationDocumentDataMenuItemsItem>>;

  /**
   * Socials Networks field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.socials_networks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials_networks: prismic.GroupField<
    Simplify<NavigationDocumentDataSocialsNetworksItem>
  >;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

/**
 * Slice for *Post → Slice zone*
 */
export type PageDocumentDataBodyTextSlice = prismic.Slice<
  "text",
  Record<string, never>,
  never
>;

type PageDocumentDataBodySlice = PageDocumentDataBodyTextSlice;

/**
 * Content for Post documents
 */
interface PageDocumentData {
  /**
   * Fecha field in *Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: date
   * - **API ID Path**: page.fecha
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  fecha: prismic.DateField;

  /**
   * H1 de la página field in *Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.h1_de_la_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  h1_de_la_pagina: prismic.TitleField;

  /**
   * Imagen del Post field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.imagen_del_post
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagen_del_post: prismic.ImageField<never>;

  /**
   * URL - Video field in *Post*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Si esta página tiene video, poner aquí la URL
   * - **API ID Path**: page.url_-_video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  "url_-_video": prismic.LinkField;

  /**
   * summary field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Resumen del artículo (obligatorio)
   * - **API ID Path**: page.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  summary: prismic.RichTextField;

  /**
   * Table of Content field in *Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Tabla de Contenidos
   * - **API ID Path**: page.table_of_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  table_of_content: prismic.TitleField;

  /**
   * Content field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice zone field in *Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<PageDocumentDataBodySlice> /**
   * SEO Título field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.seo_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  seo_title: prismic.KeyTextField;

  /**
   * SEO Descripción field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.seo_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Primary content in *Post → Slice zone → Text → Primary*
 */
export interface PostDocumentDataBodyTextSlicePrimary {
  /**
   * Text field in *Post → Slice zone → Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter your text...
   * - **API ID Path**: post.body[].text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Slice for *Post → Slice zone*
 */
export type PostDocumentDataBodyTextSlice = prismic.Slice<
  "text",
  Simplify<PostDocumentDataBodyTextSlicePrimary>,
  never
>;

/**
 * Primary content in *Post → Slice zone → Quote → Primary*
 */
export interface PostDocumentDataBodyQuoteSlicePrimary {
  /**
   * quote field in *Post → Slice zone → Quote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter quote...
   * - **API ID Path**: post.body[].quote.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;
}

/**
 * Slice for *Post → Slice zone*
 */
export type PostDocumentDataBodyQuoteSlice = prismic.Slice<
  "quote",
  Simplify<PostDocumentDataBodyQuoteSlicePrimary>,
  never
>;

/**
 * Primary content in *Post → Slice zone → Image → Primary*
 */
export interface PostDocumentDataBodyImageSlicePrimary {
  /**
   * Image field in *Post → Slice zone → Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.body[].image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Post → Slice zone → Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional image caption...
   * - **API ID Path**: post.body[].image.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField;
}

/**
 * Slice for *Post → Slice zone*
 */
export type PostDocumentDataBodyImageSlice = prismic.Slice<
  "image",
  Simplify<PostDocumentDataBodyImageSlicePrimary>,
  never
>;

/**
 * Primary content in *Post → Slice zone → Pricing Table → Primary*
 */
export interface PostDocumentDataBodyPricingTableSlicePrimary {
  /**
   * Eyebrow Headline field in *Post → Slice zone → Pricing Table → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Pricing plans
   * - **API ID Path**: post.body[].pricing_table.primary.eyebrow_headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  eyebrow_headline: prismic.RichTextField;

  /**
   * Title field in *Post → Slice zone → Pricing Table → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Choose the plan
   * - **API ID Path**: post.body[].pricing_table.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Post → Slice zone → Pricing Table → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Choose the version that works for you ...
   * - **API ID Path**: post.body[].pricing_table.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item content in *Post → Slice zone → Pricing Table → Items*
 */
export interface PostDocumentDataBodyPricingTableSliceItem {
  /**
   * Plan title field in *Post → Slice zone → Pricing Table → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Simple, Gold, Premium...
   * - **API ID Path**: post.body[].pricing_table.items.plan_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  plan_title: prismic.TitleField;

  /**
   * Price Option field in *Post → Slice zone → Pricing Table → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Free, $19, Contact us...
   * - **API ID Path**: post.body[].pricing_table.items.price_option
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  price_option: prismic.RichTextField;

  /**
   * Features field in *Post → Slice zone → Pricing Table → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A list of features using bullet list
   * - **API ID Path**: post.body[].pricing_table.items.features
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  features: prismic.RichTextField;

  /**
   * Call To Action field in *Post → Slice zone → Pricing Table → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to Signup / More info...
   * - **API ID Path**: post.body[].pricing_table.items.call_to_action
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action: prismic.LinkField;

  /**
   * Call To Action Text field in *Post → Slice zone → Pricing Table → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Start your free trial
   * - **API ID Path**: post.body[].pricing_table.items.call_to_action_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  call_to_action_text: prismic.RichTextField;
}

/**
 * Slice for *Post → Slice zone*
 */
export type PostDocumentDataBodyPricingTableSlice = prismic.Slice<
  "pricing_table",
  Simplify<PostDocumentDataBodyPricingTableSlicePrimary>,
  Simplify<PostDocumentDataBodyPricingTableSliceItem>
>;

type PostDocumentDataBodySlice =
  | PostDocumentDataBodyTextSlice
  | PostDocumentDataBodyQuoteSlice
  | PostDocumentDataBodyImageSlice
  | PostDocumentDataBodyPricingTableSlice;

/**
 * Content for Post documents
 */
interface PostDocumentData {
  /**
   * Title field in *Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Blog post title...
   * - **API ID Path**: post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Release Date field in *Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: post.release_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  release_date: prismic.DateField;

  /**
   * Author field in *Post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: Link to an author document
   * - **API ID Path**: post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField;

  /**
   * Slice zone field in *Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<PostDocumentDataBodySlice>;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<PostDocumentData>, "post", Lang>;

/**
 * Item content in *Post 2.0 (Sin Uso Al Final Mejor Usar el primero) → Slice zone → Contenido → Items*
 */
export interface Post20DocumentDataBodyContenidoSliceItem {
  /**
   * Contenido field in *Post 2.0 (Sin Uso Al Final Mejor Usar el primero) → Slice zone → Contenido → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post_20.body[].contenido.items.contenido
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contenido: prismic.RichTextField;
}

/**
 * Slice for *Post 2.0 (Sin Uso Al Final Mejor Usar el primero) → Slice zone*
 */
export type Post20DocumentDataBodyContenidoSlice = prismic.Slice<
  "contenido",
  Record<string, never>,
  Simplify<Post20DocumentDataBodyContenidoSliceItem>
>;

/**
 * Item content in *Post 2.0 (Sin Uso Al Final Mejor Usar el primero) → Slice zone → Imagen → Items*
 */
export interface Post20DocumentDataBodyImagenSliceItem {
  /**
   * Image field in *Post 2.0 (Sin Uso Al Final Mejor Usar el primero) → Slice zone → Imagen → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post_20.body[].imagen.items.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Slice for *Post 2.0 (Sin Uso Al Final Mejor Usar el primero) → Slice zone*
 */
export type Post20DocumentDataBodyImagenSlice = prismic.Slice<
  "imagen",
  Record<string, never>,
  Simplify<Post20DocumentDataBodyImagenSliceItem>
>;

type Post20DocumentDataBodySlice =
  | Post20DocumentDataBodyContenidoSlice
  | Post20DocumentDataBodyImagenSlice;

/**
 * Content for Post 2.0 (Sin Uso Al Final Mejor Usar el primero) documents
 */
interface Post20DocumentData {
  /**
   * H1 de la página field in *Post 2.0 (Sin Uso Al Final Mejor Usar el primero)*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: post_20.h1_de_la_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  h1_de_la_pagina: prismic.TitleField;

  /**
   * Imagen del Post field in *Post 2.0 (Sin Uso Al Final Mejor Usar el primero)*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post_20.imagen_del_post
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagen_del_post: prismic.ImageField<never>;

  /**
   * URL - Video field in *Post 2.0 (Sin Uso Al Final Mejor Usar el primero)*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Si esta página tiene video, poner aquí la URL
   * - **API ID Path**: post_20.url_-_video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  "url_-_video": prismic.LinkField;

  /**
   * Summary field in *Post 2.0 (Sin Uso Al Final Mejor Usar el primero)*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Resumen del artículo (obligatorio)
   * - **API ID Path**: post_20.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  summary: prismic.RichTextField;

  /**
   * Slice zone field in *Post 2.0 (Sin Uso Al Final Mejor Usar el primero)*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post_20.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<Post20DocumentDataBodySlice> /**
   * SEO Título field in *Post 2.0 (Sin Uso Al Final Mejor Usar el primero)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post_20.seo_titulo
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  seo_titulo: prismic.KeyTextField;

  /**
   * SEO Descripción field in *Post 2.0 (Sin Uso Al Final Mejor Usar el primero)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post_20.seo_descripcion
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_descripcion: prismic.KeyTextField;
}

/**
 * Post 2.0 (Sin Uso Al Final Mejor Usar el primero) document from Prismic
 *
 * - **API ID**: `post_20`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Post20Document<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<Post20DocumentData>, "post_20", Lang>;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * s field in *Product*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: product.s
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  s: prismic.TitleField;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

interface PruebaDocumentData {}

/**
 * Prueba document from Prismic
 *
 * - **API ID**: `prueba`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PruebaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PruebaDocumentData>,
    "prueba",
    Lang
  >;

/**
 * Item in *Settings → Background Images Array*
 */
export interface SettingsDocumentDataBackgroundImagesArrayItem {
  /**
   * Image field in *Settings → Background Images Array*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.background_images_array[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type SettingsDocumentDataBodySlice = never;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Favicon field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.favicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  favicon: prismic.ImageField<never>;

  /**
   * Background Images Array field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.background_images_array[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  background_images_array: prismic.GroupField<
    Simplify<SettingsDocumentDataBackgroundImagesArrayItem>
  >;

  /**
   * Slice zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<SettingsDocumentDataBodySlice>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Image of Review field in *Testimonial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.image_of_review
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_of_review: prismic.ImageField<never>;

  /**
   * Name of Reviewer field in *Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.name_of_reviewer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name_of_reviewer: prismic.RichTextField;

  /**
   * Description of review field in *Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.description_of_review
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_of_review: prismic.RichTextField;

  /**
   * CTA to watch video field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.cta_to_watch_video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_to_watch_video: prismic.KeyTextField;

  /**
   * Video Popup field in *Testimonial*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.video_popup
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_popup: prismic.LinkField;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TestimonialDocumentData>,
    "testimonial",
    Lang
  >;

/**
 * Content for Testimonials documents
 */
interface TestimonialsDocumentData {
  /**
   * All Testimonials Content Relationship field in *Testimonials*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.all_testimonials_content_relationship
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  all_testimonials_content_relationship: prismic.ContentRelationshipField<"testimonials_all_of_th">;

  /**
   * All  Testimonials field in *Testimonials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.all__testimonials
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  all__testimonials: prismic.LinkField;
}

/**
 * Testimonials document from Prismic
 *
 * - **API ID**: `testimonials`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TestimonialsDocumentData>,
    "testimonials",
    Lang
  >;

/**
 * Primary content in *Testimonials All of them → Slice zone → Video Reviews → Primary*
 */
export interface TestimonialsAllOfThDocumentDataBodyVideoReviewsSlicePrimary {
  /**
   * Intro To Reviews field in *Testimonials All of them → Slice zone → Video Reviews → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_all_of_th.body[].video_reviews.primary.intro_to_reviews
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  intro_to_reviews: prismic.RichTextField;
}

/**
 * Item content in *Testimonials All of them → Slice zone → Video Reviews → Items*
 */
export interface TestimonialsAllOfThDocumentDataBodyVideoReviewsSliceItem {
  /**
   * Image of Review field in *Testimonials All of them → Slice zone → Video Reviews → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_all_of_th.body[].video_reviews.items.image_of_review
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_of_review: prismic.ImageField<never>;

  /**
   * Name of Reviwer field in *Testimonials All of them → Slice zone → Video Reviews → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_all_of_th.body[].video_reviews.items.name_of_reviwer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name_of_reviwer: prismic.RichTextField;

  /**
   * Description of review field in *Testimonials All of them → Slice zone → Video Reviews → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_all_of_th.body[].video_reviews.items.description_of_review
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_of_review: prismic.RichTextField;

  /**
   * CTA to watch video field in *Testimonials All of them → Slice zone → Video Reviews → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_all_of_th.body[].video_reviews.items.cta_to_watch_video
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_to_watch_video: prismic.RichTextField;

  /**
   * Video PopUp field in *Testimonials All of them → Slice zone → Video Reviews → Items*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_all_of_th.body[].video_reviews.items.video_popup
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video_popup: prismic.EmbedField;
}

/**
 * Slice for *Testimonials All of them → Slice zone*
 */
export type TestimonialsAllOfThDocumentDataBodyVideoReviewsSlice =
  prismic.Slice<
    "video_reviews",
    Simplify<TestimonialsAllOfThDocumentDataBodyVideoReviewsSlicePrimary>,
    Simplify<TestimonialsAllOfThDocumentDataBodyVideoReviewsSliceItem>
  >;

type TestimonialsAllOfThDocumentDataBodySlice =
  TestimonialsAllOfThDocumentDataBodyVideoReviewsSlice;

/**
 * Content for Testimonials All of them documents
 */
interface TestimonialsAllOfThDocumentData {
  /**
   * Introduction Text field in *Testimonials All of them*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_all_of_th.introduction_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  introduction_text: prismic.RichTextField;

  /**
   * Slice zone field in *Testimonials All of them*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_all_of_th.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<TestimonialsAllOfThDocumentDataBodySlice>;
}

/**
 * Testimonials All of them document from Prismic
 *
 * - **API ID**: `testimonials_all_of_th`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialsAllOfThDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialsAllOfThDocumentData>,
    "testimonials_all_of_th",
    Lang
  >;

interface VideoReviewsDocumentData {}

/**
 * Video Reviews document from Prismic
 *
 * - **API ID**: `video_reviews`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideoReviewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<VideoReviewsDocumentData>,
    "video_reviews",
    Lang
  >;

export type AllDocumentTypes =
  | BlogListingDocument
  | CtaIframeDocument
  | EntradaPostDocument
  | FooterDocument
  | HomeDocument
  | HomepageDocument
  | LandingPageDocument
  | NavigationDocument
  | PageDocument
  | PostDocument
  | Post20Document
  | ProductDocument
  | PruebaDocument
  | SettingsDocument
  | TestimonialDocument
  | TestimonialsDocument
  | TestimonialsAllOfThDocument
  | VideoReviewsDocument;

/**
 * Primary content in *Iframe → Primary*
 */
export interface IframeSliceDefaultPrimary {
  /**
   * iFrame field in *Iframe → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: iframe.primary.iframe
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  iframe: prismic.KeyTextField;

  /**
   * Max Width field in *Iframe → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: iframe.primary.max_width
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  max_width: prismic.NumberField;

  /**
   * Height field in *Iframe → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: iframe.primary.height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  height: prismic.NumberField;
}

/**
 * Default variation for Iframe Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IframeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IframeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Iframe*
 */
type IframeSliceVariation = IframeSliceDefault;

/**
 * Iframe Shared Slice
 *
 * - **API ID**: `iframe`
 * - **Description**: Iframe
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IframeSlice = prismic.SharedSlice<"iframe", IframeSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogListingDocument,
      BlogListingDocumentData,
      CtaIframeDocument,
      CtaIframeDocumentData,
      EntradaPostDocument,
      EntradaPostDocumentData,
      EntradaPostDocumentDataBodySlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataLegalItem,
      FooterDocumentDataBodyCallToActionSlicePrimary,
      FooterDocumentDataBodyBloquesSlicePrimary,
      FooterDocumentDataBodyBloquesSliceItem,
      FooterDocumentDataBodySlice,
      HomeDocument,
      HomeDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataBodyHeroSlicePrimary,
      HomepageDocumentDataBodyCallToActionSlicePrimary,
      HomepageDocumentDataBodySlice,
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataBodyHeroLandingSlicePrimary,
      LandingPageDocumentDataBodyCallToActionSlicePrimary,
      LandingPageDocumentDataBodyContentWithImageSlicePrimary,
      LandingPageDocumentDataBodyVideoReviewsSlicePrimary,
      LandingPageDocumentDataBodyVideoReviewsSliceItem,
      LandingPageDocumentDataBodyLeadMagnetBookSlicePrimary,
      LandingPageDocumentDataBodyFaqsSlicePrimary,
      LandingPageDocumentDataBodyFaqsSliceItem,
      LandingPageDocumentDataBodyTeamSlicePrimary,
      LandingPageDocumentDataBodyTeamSliceItem,
      LandingPageDocumentDataBodyTestimonialsSlicePrimary,
      LandingPageDocumentDataBodyCtaIframeSlicePrimary,
      LandingPageDocumentDataBodyBookASessionScriptSlicePrimary,
      LandingPageDocumentDataBodySlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataMenuItemsItem,
      NavigationDocumentDataSocialsNetworksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataBodySlice,
      PostDocument,
      PostDocumentData,
      PostDocumentDataBodyTextSlicePrimary,
      PostDocumentDataBodyQuoteSlicePrimary,
      PostDocumentDataBodyImageSlicePrimary,
      PostDocumentDataBodyPricingTableSlicePrimary,
      PostDocumentDataBodyPricingTableSliceItem,
      PostDocumentDataBodySlice,
      Post20Document,
      Post20DocumentData,
      Post20DocumentDataBodyContenidoSliceItem,
      Post20DocumentDataBodyImagenSliceItem,
      Post20DocumentDataBodySlice,
      ProductDocument,
      ProductDocumentData,
      PruebaDocument,
      PruebaDocumentData,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataBackgroundImagesArrayItem,
      SettingsDocumentDataBodySlice,
      TestimonialDocument,
      TestimonialDocumentData,
      TestimonialsDocument,
      TestimonialsDocumentData,
      TestimonialsAllOfThDocument,
      TestimonialsAllOfThDocumentData,
      TestimonialsAllOfThDocumentDataBodyVideoReviewsSlicePrimary,
      TestimonialsAllOfThDocumentDataBodyVideoReviewsSliceItem,
      TestimonialsAllOfThDocumentDataBodySlice,
      VideoReviewsDocument,
      VideoReviewsDocumentData,
      AllDocumentTypes,
      IframeSlice,
      IframeSliceDefaultPrimary,
      IframeSliceVariation,
      IframeSliceDefault
    };
  }
}
